// Code generated by hand (instead of protoc). DO NOT EDIT.
// Source: user.proto

package user

import (
	"time"
)

// User 用户消息结构
type User struct {
	ID        uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name      string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Email     string    `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	Phone     string    `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone"`
	Age       int32     `protobuf:"varint,5,opt,name=age,proto3" json:"age"`
	CreatedAt time.Time `protobuf:"bytes,6,opt,name=created_at,proto3,stdtime" json:"created_at"`
	UpdatedAt time.Time `protobuf:"bytes,7,opt,name=updated_at,proto3,stdtime" json:"updated_at"`
}

// CreateUserRequest 创建用户请求
type CreateUserRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email"`
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone"`
	Age   int32  `protobuf:"varint,4,opt,name=age,proto3" json:"age"`
}

// CreateUserResponse 创建用户响应
type CreateUserResponse struct {
	User    *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

// GetUserRequest 获取用户请求
type GetUserRequest struct {
	ID uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

// GetUserResponse 获取用户响应
type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
}

// UpdateUserRequest 更新用户请求
type UpdateUserRequest struct {
	ID    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone"`
	Age   int32  `protobuf:"varint,5,opt,name=age,proto3" json:"age"`
}

// UpdateUserResponse 更新用户响应
type UpdateUserResponse struct {
	User    *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

// DeleteUserRequest 删除用户请求
type DeleteUserRequest struct {
	ID uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

// DeleteUserResponse 删除用户响应
type DeleteUserResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
}

// ListUsersRequest 列出用户请求
type ListUsersRequest struct {
	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,proto3" json:"page_size"`
}

// ListUsersResponse 列出用户响应
type ListUsersResponse struct {
	Users    []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`
	Total    int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Page     int32   `protobuf:"varint,3,opt,name=page,proto3" json:"page"`
	PageSize int32   `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size"`
}
