// Code generated by hand (instead of protoc-gen-go-grpc). DO NOT EDIT.
// Source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// UserServiceClient 用户服务客户端接口
type UserServiceClient interface {
	// CreateUser 创建用户
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// GetUser 获取用户
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// UpdateUser 更新用户
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	// DeleteUser 删除用户
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// ListUsers 列出用户
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

// userServiceClient 用户服务客户端实现
type userServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewUserServiceClient 创建用户服务客户端
func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc: cc}
}

// CreateUser 创建用户实现
func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUser 获取用户实现
func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateUser 更新用户实现
func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteUser 删除用户实现
func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListUsers 列出用户实现
func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer 用户服务服务端接口
type UserServiceServer interface {
	// CreateUser 创建用户
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// GetUser 获取用户
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// UpdateUser 更新用户
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// DeleteUser 删除用户
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// ListUsers 列出用户
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

// RegisterUserServiceServer 注册用户服务
func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

// _UserService_CreateUser_Handler CreateUser 方法处理器
func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor != nil {
		info := &grpc.UnaryServerInfo{
			Server:     srv,
			FullMethod: "/user.UserService/CreateUser",
		}
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
		}
		return interceptor(ctx, in, info, handler)
	}
	return srv.(UserServiceServer).CreateUser(ctx, in)
}

// _UserService_GetUser_Handler GetUser 方法处理器
func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor != nil {
		info := &grpc.UnaryServerInfo{
			Server:     srv,
			FullMethod: "/user.UserService/GetUser",
		}
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
		}
		return interceptor(ctx, in, info, handler)
	}
	return srv.(UserServiceServer).GetUser(ctx, in)
}

// _UserService_UpdateUser_Handler UpdateUser 方法处理器
func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor != nil {
		info := &grpc.UnaryServerInfo{
			Server:     srv,
			FullMethod: "/user.UserService/UpdateUser",
		}
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
		}
		return interceptor(ctx, in, info, handler)
	}
	return srv.(UserServiceServer).UpdateUser(ctx, in)
}

// _UserService_DeleteUser_Handler DeleteUser 方法处理器
func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor != nil {
		info := &grpc.UnaryServerInfo{
			Server:     srv,
			FullMethod: "/user.UserService/DeleteUser",
		}
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
		}
		return interceptor(ctx, in, info, handler)
	}
	return srv.(UserServiceServer).DeleteUser(ctx, in)
}

// _UserService_ListUsers_Handler ListUsers 方法处理器
func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor != nil {
		info := &grpc.UnaryServerInfo{
			Server:     srv,
			FullMethod: "/user.UserService/ListUsers",
		}
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
		}
		return interceptor(ctx, in, info, handler)
	}
	return srv.(UserServiceServer).ListUsers(ctx, in)
}
