// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: post.proto

package postservice

import (
	"context"

	"blog-post-service/rpc/types/post"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IsSuccess         = post.IsSuccess
	PostDto           = post.PostDto
	PostDtoConditions = post.PostDtoConditions
	PostDtoList       = post.PostDtoList
	PostId            = post.PostId

	PostService interface {
		// 新增文章
		CreatePost(ctx context.Context, in *PostDto, opts ...grpc.CallOption) (*IsSuccess, error)
		// 获取文章
		GetPost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*PostDto, error)
		// 多条件查询文章 不传入就是查询所有
		GetPostsByConditions(ctx context.Context, in *PostDtoConditions, opts ...grpc.CallOption) (*PostDtoList, error)
		// 删除文章
		DeletePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*IsSuccess, error)
		// 更新文章
		UpdatePost(ctx context.Context, in *PostDto, opts ...grpc.CallOption) (*IsSuccess, error)
	}

	defaultPostService struct {
		cli zrpc.Client
	}
)

func NewPostService(cli zrpc.Client) PostService {
	return &defaultPostService{
		cli: cli,
	}
}

// 新增文章
func (m *defaultPostService) CreatePost(ctx context.Context, in *PostDto, opts ...grpc.CallOption) (*IsSuccess, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

// 获取文章
func (m *defaultPostService) GetPost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*PostDto, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.GetPost(ctx, in, opts...)
}

// 多条件查询文章 不传入就是查询所有
func (m *defaultPostService) GetPostsByConditions(ctx context.Context, in *PostDtoConditions, opts ...grpc.CallOption) (*PostDtoList, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.GetPostsByConditions(ctx, in, opts...)
}

// 删除文章
func (m *defaultPostService) DeletePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*IsSuccess, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

// 更新文章
func (m *defaultPostService) UpdatePost(ctx context.Context, in *PostDto, opts ...grpc.CallOption) (*IsSuccess, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}
