// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type MsgVo struct {
	Msg string `json:"msg"`
}

type PathId struct {
	Id int `path:"id"`
}

// 文章数据传输对象
type PostDto struct {
	Id      int    `json:"id,omitempty"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Summary string `json:"summary"`
	//非必填，默认值为空字符串
	Cover string `json:"cover,omitempty"`
	//非必填，默认值为0
	ViewCount int `json:"view_count,omitempty"`
	//非必填，默认值为0
	LikeCount int   `json:"like_count,omitempty"`
	UserID    int64 `json:"user_id"`
}

type PostVo struct {
	Id        int    `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Summary   string `json:"summary"`
	Cover     string `json:"cover"`
	ViewCount int    `json:"view_count"`
	LikeCount int    `json:"like_count"`
	UserID    int64  `json:"user_id"`
}
