// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userservice

import (
	"context"

	"blog_user_service/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdDto          = user.IdDto
	IsSuccess      = user.IsSuccess
	LoginDto       = user.LoginDto
	LoginResponse  = user.LoginResponse
	PageInfoDto    = user.PageInfoDto
	RegisterDto    = user.RegisterDto
	UserInfoVo     = user.UserInfoVo
	UserInfoVoList = user.UserInfoVoList
	UsernameDto    = user.UsernameDto

	UserService interface {
		// 注册
		Register(ctx context.Context, in *RegisterDto, opts ...grpc.CallOption) (*UserInfoVo, error)
		// 登录
		Login(ctx context.Context, in *LoginDto, opts ...grpc.CallOption) (*LoginResponse, error)
		// 分页查询用户
		ListUser(ctx context.Context, in *PageInfoDto, opts ...grpc.CallOption) (*UserInfoVoList, error)
		// 根据用户名获取用户信息
		GetUserByUsername(ctx context.Context, in *UsernameDto, opts ...grpc.CallOption) (*UserInfoVo, error)
		// 根据id查询用户
		GetUserById(ctx context.Context, in *IdDto, opts ...grpc.CallOption) (*UserInfoVo, error)
		UpdateUserInfo(ctx context.Context, in *UserInfoVo, opts ...grpc.CallOption) (*IsSuccess, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 注册
func (m *defaultUserService) Register(ctx context.Context, in *RegisterDto, opts ...grpc.CallOption) (*UserInfoVo, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 登录
func (m *defaultUserService) Login(ctx context.Context, in *LoginDto, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 分页查询用户
func (m *defaultUserService) ListUser(ctx context.Context, in *PageInfoDto, opts ...grpc.CallOption) (*UserInfoVoList, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ListUser(ctx, in, opts...)
}

// 根据用户名获取用户信息
func (m *defaultUserService) GetUserByUsername(ctx context.Context, in *UsernameDto, opts ...grpc.CallOption) (*UserInfoVo, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserByUsername(ctx, in, opts...)
}

// 根据id查询用户
func (m *defaultUserService) GetUserById(ctx context.Context, in *IdDto, opts ...grpc.CallOption) (*UserInfoVo, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserInfo(ctx context.Context, in *UserInfoVo, opts ...grpc.CallOption) (*IsSuccess, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}
