// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: post.proto

package server

import (
	"context"

	"blog-post-service/rpc/internal/logic"
	"blog-post-service/rpc/internal/svc"
	"blog-post-service/rpc/types/post"
)

type PostServiceServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedPostServiceServer
}

func NewPostServiceServer(svcCtx *svc.ServiceContext) *PostServiceServer {
	return &PostServiceServer{
		svcCtx: svcCtx,
	}
}

// 新增文章
func (s *PostServiceServer) CreatePost(ctx context.Context, in *post.PostDto) (*post.IsSuccess, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

// 获取文章
func (s *PostServiceServer) GetPost(ctx context.Context, in *post.PostId) (*post.PostDto, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

// 多条件查询文章 不传入就是查询所有
func (s *PostServiceServer) GetPostsByConditions(ctx context.Context, in *post.PostDtoConditions) (*post.PostDtoList, error) {
	l := logic.NewGetPostsByConditionsLogic(ctx, s.svcCtx)
	return l.GetPostsByConditions(in)
}

// 删除文章
func (s *PostServiceServer) DeletePost(ctx context.Context, in *post.PostId) (*post.IsSuccess, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

// 更新文章
func (s *PostServiceServer) UpdatePost(ctx context.Context, in *post.PostDto) (*post.IsSuccess, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}
