// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"blog_user_service/rpc/internal/logic"
	"blog_user_service/rpc/internal/svc"
	"blog_user_service/rpc/types/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *UserServiceServer) Register(ctx context.Context, in *user.RegisterDto) (*user.UserInfoVo, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 登录
func (s *UserServiceServer) Login(ctx context.Context, in *user.LoginDto) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 分页查询用户
func (s *UserServiceServer) ListUser(ctx context.Context, in *user.PageInfoDto) (*user.UserInfoVoList, error) {
	l := logic.NewListUserLogic(ctx, s.svcCtx)
	return l.ListUser(in)
}

// 根据用户名获取用户信息
func (s *UserServiceServer) GetUserByUsername(ctx context.Context, in *user.UsernameDto) (*user.UserInfoVo, error) {
	l := logic.NewGetUserByUsernameLogic(ctx, s.svcCtx)
	return l.GetUserByUsername(in)
}

// 根据id查询用户
func (s *UserServiceServer) GetUserById(ctx context.Context, in *user.IdDto) (*user.UserInfoVo, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *UserServiceServer) UpdateUserInfo(ctx context.Context, in *user.UserInfoVo) (*user.IsSuccess, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}
