// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginDto struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginVo struct {
	Token string `json:"token"`
}

type QueryDto struct {
	Id int64 `json:"id"`
}

type QueryPathDto struct {
	Id int64 `path:"id"`
}

type QueryVo struct {
	User User `json:"user"`
}

type RegisterDto struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UpdateUserVo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Age         int    `json:"age"`
	Description string `json:"description"`
	Nickname    string `json:"nickname"`
	Role        string `json:"role"`
}

type User struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Age         int    `json:"age"`
	Description string `json:"description"`
	Nickname    string `json:"nickname"`
	Role        string `json:"role"`
}
